USE training_center;

CREATE TABLE STUDENT (
    student_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(30) CHARACTER SET utf8 NOT NULL,
    first_name VARCHAR(30) CHARACTER SET utf8 NOT NULL,
    middle_name VARCHAR(30) CHARACTER SET utf8
) engine=InnoDB;

CREATE TABLE COMPANY (
    company_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) CHARACTER SET utf8 NOT NULL,
    address VARCHAR(255) CHARACTER SET utf8
) engine=InnoDB;

CREATE TABLE TEACHER (
    teacher_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(30) CHARACTER SET utf8 NOT NULL,
    first_name VARCHAR(30) CHARACTER SET utf8 NOT NULL,
    middle_name VARCHAR(30) CHARACTER SET utf8   
) engine=InnoDB;

CREATE TABLE COURSE (
    course_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    name VARCHAR(60) CHARACTER SET utf8 NOT NULL
) engine=InnoDB;
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_COMPANY FOREIGN KEY (company_id) REFERENCES COMPANY(company_id);

CREATE TABLE STUDENT_COURSE (
    student_course_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    student_id INT UNSIGNED NOT NULL,
    course_id INT UNSIGNED NOT NULL
) engine=InnoDB;
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT FK_STUDENT_COURSE_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(student_id);
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT FK_STUDENT_COURSE_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(course_id);

CREATE TABLE LESSON (
    lesson_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id INT UNSIGNED NOT NULL,
    teacher_id INT UNSIGNED NOT NULL,
    time TIME NOT NULL,
    duration TIME NOT NULL,
    period INT NOT NULL,
    date_start DATE NOT NULL,
    date_end DATE NOT NULL
) engine=InnoDB;
ALTER TABLE LESSON ADD CONSTRAINT FK_LESSON_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(course_id);
ALTER TABLE LESSON ADD CONSTRAINT FK_LESSON_TEACHER FOREIGN KEY (teacher_id) REFERENCES TEACHER(teacher_id);